version: "3"
services:
  back:
    build: "./back"
    env_file:
      - .env

  front:
    build: "."
    env_file:
      - .env

  nginx:
    restart: unless-stopped
    depends_on:
      - front
      - back
    build:
      context: ./nginx
    ports:
      - "${EXPOSED_PORT:-80}:80"

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: immersion-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data
