version: "3"
services:
  back:
    build: "./back"
    ports:
      - "5555:1234"
    env_file:
      - .env

  front:
    build: "."
    env_file:
      - .env

  nginx:
    restart: unless-stopped
    depends_on:
      - front
      - back
    build:
      context: ./nginx
    ports:
      - "${EXPOSED_PORT:-80}:80"
