version: "3"
services: 
    back:
        build: "./back"
        ports: 
            - "8080:8080"
    front:
        build: "."
        ports:
            - "3000:5000"
        environment: 
            BACKEND_URL: "http://back:8080/"
    