version: "3"
services: 
  back:
    build: "./back"
    ports:
      - "5555:1234"
    env_file:
      - .env.back

  front:
    build: "."
    env_file:
      - .env.front

  nginx:
    restart: unless-stopped
    depends_on:
      - front
      - back
    build:
      context: ./nginx
    ports:
      - 80:80
