version: "3"

x-logging-config:
  &logging-config
  logging:
    driver: loki
    options:
      loki-url: http://${LOKI_HOST:-localhost:9092}/loki/api/v1/push
      loki-retries: "5"
      loki-external-labels: "environment=${ENV_TYPE:-unknown},container_name={{.Name}}"

services:
  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./docker-data/pipelines/log:/var/log/pipelines
    network_mode: host
    environment:
      LOKI_HOST: "${LOKI_HOST:-localhost:9092}"
      ENV_TYPE: "${ENV_TYPE:-unknown}"
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml -print-config-stderr

  back:
    <<: *logging-config

  front:
    <<: *logging-config

  pipelines:
    <<: *logging-config

  nginx:
    <<: *logging-config

  postgres:
    <<: *logging-config

  adminer:
    <<: *logging-config

