version: "3"
services:
  back:
    build: "./back"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  front:
    build: "."
    env_file:
      - .env

  nginx:
    restart: unless-stopped
    depends_on:
      - front
      - back
    build:
      context: ./nginx
      args:
        - ENV_TYPE=${ENV_TYPE:-develop}
        - DOMAIN=${DOMAIN:-domain.tld}
        - LETSENCRYPT_MAIL=${LETSENCRYPT_MAIL:-not_provided@mail.com}
    ports:
      - "${EXPOSED_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/

  postgres:
    image: postgis/postgis:13-master
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: immersion-db
      POSTGRES_USER: immersion
      POSTGRES_PASSWORD: pg-password
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT:-8090}:8080"
