version: "3"
services: 
    back:
        build: "./back"
        ports: 
            - "5555:1234"
    front:
        build: "."
        ports:
            - "3000:5000"
        environment: 
            BACKEND_URL: "http://back:5555/"
    
