server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://${LOKI_HOST}/loki/api/v1/push

scrape_configs:
- job_name: promtail-immersion-facile
  static_configs:
  - targets:
      - localhost
    labels:
      job: pipelines
      environment: ${ENV_TYPE}
      __path__: /var/log/pipelines/*log
