name: Back CI
on: [push]
jobs:
  Back-CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: cd back && npm ci
      - name: Run tests
        run: cd back && npm run test:all
      - name: Typecheck and Build
        run: cd back && npm run build
