name: "Build front, back and deploy"

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  validation:
    uses: ./.github/workflows/fullcheck.yml

  build-front-artefact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build front
        run: pnpm front build-scalingo
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: front-build-${{github.sha}}
          path: front/front-build.tar.gz

  build-back-artefact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build backend
        run: pnpm back build
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: back-build-${{github.sha}}
          path: back/back-build.tar.gz

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: [validation, build-front-artefact, build-back-artefact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      envType: "dev"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN_V2 }}

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: [build-front-artefact, build-back-artefact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      envType: "staging"
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN_V2 }}
