name: "Fullcheck of the project - (except integration tests)"

on:
  push:
    branches-ignore:
      - dev
      - staging
      - main

  workflow_call:

jobs:
  validation:
    name: ""
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        command:
          ["pnpm fast-checks", "pnpm typecheck", "pnpm back test", "pnpm lint"]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: ${{matrix.command}}
        env:
          COMMAND: ${{matrix.command}}
        run: |
          STORAGE_FULL_PATH=$(pwd)/back/storage
          mkdir -p $STORAGE_FULL_PATH/tmp/     
          STORAGE_ROOT=$STORAGE_FULL_PATH $COMMAND
