name: Copy DB PE vers sur scalingo prod secnum

on:
  workflow_dispatch:
    inputs:
      application-name:
        required: true
        type: string

jobs:
  dump-from-PE-and-restore-to-secnum-prod:
    runs-on: ubuntu-latest
    name: Dump and restore the remote database data.
    env:
      REMOTE_DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}
      DATABASE_VAR: "$DATABASE_URL"

    steps:
      - name: Install scalingo CLI
        run: |
          wget -qO- https://cli-dl.scalingo.com/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN_SECNUM }}

      - name: Dump the remote database data and restore it to the local database.
        run: >-
          scalingo --region osc-secnum-fr1 --app ${{ inputs.application-name }} run bash -c "echo 'Installing pgsql-client' &&
          dbclient-fetcher pgsql &&
          echo 'Dumping data' &&
          pg_dump --clean --format c --no-owner --no-privileges --no-comments --exclude-schema 'information_schema' --exclude-schema '^pg_*' --dbname $REMOTE_DATABASE_URL --file dump.pgsql &&
          echo 'Finished dumping data' &&
          pg_restore --clean --verbose --no-owner --no-privileges --no-comments --dbname "$DATABASE_VAR" dump.pgsql; 
          exit 0"
