name: Setup - Clevercloud get secrets

on:
  workflow_dispatch:

jobs:
  login-for-repository-setup:
    runs-on: ubuntu-latest
    container:
      image: clevercloud/clever-tools
    steps:
      - name: Login to get token
        run: |
          echo 'Copy the given url in your browser, log in, setup the CLEVER_TOKEN & CLEVER_SECRET and optionally CLEVER_ORG_ID repository variables'
          clever login
